In [ ]:
import pandas as pd

filename = "/content/diabetes.csv"
df = pd.read_csv(filename)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
# La variable de 'Glucose' y 'BloodPressure' se estimo en valores por sobre cero, debido a que se
# asume que los valores normales considerados para una persona viva no pueden ser menores.
filter1 = df["Glucose"] > 0
filter3 = df["BloodPressure"] > 0
filter4 = df["BMI"] != 0

df1 = df.loc[filter1 & filter3 & filter4, :]
df1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
# En cuanto al filtro 'Pregnancies', se decidio no filtrar por dicha variable, debido a que en consideracion a otros casos encontrados en el df (personas con mas de 10 embarazos
# y entre los mismos rangos de edad) no se considero 'imposible' que hubieran casos con mas de 14 embarazos. Ademas, considerando la edad promedio de la menarquia (12 anios)
# aquellos casos son perfectamente posibles en relacion a la edad de dichas personas.

print("Aqui podemos ver los casos extremos encontrados en el df:")

p_filter = df['Pregnancies'] >= 14

df1 = df.loc[p_filter, :]
df1

Aqui podemos ver los casos extremos encontrados en el df:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
88,15,136,70,32,110,37.1,0.153,43,1
159,17,163,72,41,114,40.9,0.817,47,1
298,14,100,78,25,184,36.6,0.412,46,1
455,14,175,62,30,0,33.6,0.212,38,1

In [ ]:
print("Aqui podemos ver las edades de los casos con mas de 10 embarazos dentro del data frame")
# Como se puede ver, la cantidad de casos con mas de 10 embarazos no es menor...
p_filter1 = df['Pregnancies'] > 10

df2 = df.loc[p_filter1, 'Age' :]
df2

In [ ]:
df1.to_csv(path_or_buf='diabetes_filtrado.csv',index = False)