Crear 14 vectores (listas) en variables diferentes que tendrán los siguientes parámetros, rellenarlos con 20 datos.

Sexo 
Género de música (6 tipos de género)
Género de película (5 tipos diferentes)
Edad 
Salario (si es menor de edad NaN o NaT)
Rango salario (1 a 320k Bajo, 320 a 700 Medio, Mayor a 700 Alto)
hijos
Localidad donde Vive
Estado civil (casado, soltero, unión civil)
Peso
Altura
Grado de educación (actual) menores a 4 años NaN o NaT
País de nacimiento (al menos 4 países)
Deporte (poner 4 deportes mínimo en caso de edad NaN o NaT)

A partir, de los vectores creados generar un dataframe y guardarlo en un csv

In [ ]:
import numpy as np
import pandas as pd 
import random

Sexo=["Femenino","Masculino"]
Genero_Musical=["Jazz","Reggaeton","Rap","Romantica","Cumbia","Tecno","Electronica"]
Genero_Pelicula=["Terror","Suspenso","Accion","Entretenimiento","Romantica","Musical"]
edades = random.sample(range(80), 20)

Salario=[]
Altura=[]
for i in edades:
  Altura.append(int(input(f"Ingrese la altura para {i}: ")))
  if i>= 18:
    Salario.append(int(input("Ingrese Salario: ")))
  else:
    Salario.append(0)


contar=0
Rango_Salario=[]
while contar < len(Salario): 
  if Salario[contar]<=3500:
    Rango_Salario.append("LOW")
    print("Vamos bien")
  elif: 

  else:
    
  contar=contar+1




#Rango_salario=[np.nan, "Menor a $350.000", "Entre $350.00 y $599.999", "Entre $600.000 y 899.999", "Superior a $900.000"] #Depende de salario y de la edad


Cant_Hijos=[0,1,2,3,4,5,6]
Localidad=["Peñalolen","Las Condes","Maipu","La Florida","Ñuñoa","Colina"]
Estado_Civil=["Casado","Soltero","Union Civil",np.nan]

#Altura=[1.70,1.55,1.68,2.04,2.01,1.77,1.10]
Grado_educ=[np.nan, "Básica Incompleta", "Básica Completa", "Media Incompleta", "Media Completa", "Universitaria Completa", "Técnica Completa"]
Pais_Nac=["Chile","Bolivia","Inglaterra","Gales","Argentina","Brasil","Dinamarca","Grecia"]
Deporte=["Tenis", "Futbol", "Padel", "Basketball", "Badminton", "Voleibol", "Patinaje"]

Ingrese Salario: 1
Ingrese Salario: 2
Ingrese Salario: 3
Ingrese Salario: 4
Ingrese Salario: 5
Ingrese Salario: 6
Ingrese Salario: 7
Ingrese Salario: 8
Ingrese Salario: 9
Ingrese Salario: 1000
Ingrese Salario: 2000
Ingrese Salario: 3000
Ingrese Salario: 7000
Ingrese Salario: 5000
Ingrese Salario: 2000
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien
Vamos bien

In [1]:
import numpy as np
import pandas as pd 
import random

In [9]:

Sexo=["Femenino","Masculino"]
Genero_Musical=["Jazz","Reggaeton","Rap","Romantica","Cumbia","Tecno","Electronica"]
Genero_Pelicula=["Terror","Suspenso","Accion","Entretenimiento","Romantica","Musical"]
edades = random.sample(range(80), 3)

Salario=[]
Altura=[]
Hijos=[]
for i in edades:
  Altura.append(float(input(f"Ingrese la altura para {i}: ")))
  if i>= 18:
    Salario.append(int(input("Ingrese Salario: ")))
    Hijos.append(int(input('Ingrese la cantidad de hijos: ')))
  else:
    Salario.append(0)
    Hijos.append(0)


contar=0
Rango_Salario=[]
while contar < len(Salario): 
  if Salario[contar]<=320000:
    Rango_Salario.append("LOW")
  elif (Salario[contar]<=700000) & (Salario[contar] > 320000):
    Rango_Salario.append("MEDIUM")
  elif (Salario[contar]>700000):
    Rango_Salario.append("HIGH")
  contar=contar+1

Localidad=["Peñalolen","Las Condes","Maipu","La Florida","Ñuñoa","Colina"]
Pais_Nac=["Chile","Bolivia","Inglaterra","Gales","Argentina","Brasil","Dinamarca","Grecia"]
Deporte=["Tenis", "Futbol", "Padel", "Basketball", "Badminton", "Voleibol", "Patinaje"]
Estado_Civil=["Casado","Soltero","Union Civil",np.nan]
Grado_educ=[np.nan, "Básica Incompleta", "Básica Completa", "Media Incompleta", "Media Completa", "Universitaria Completa", "Técnica Completa"]

lista1=[]
lista2=[]
lista3=[]
lista4=[]
lista5=[]
lista6=[]
lista7=[]
lista8=[]
for i in range(3):
  choice1=random.choice(Localidad)
  lista1.append(choice1)
  choice2=random.choice(Pais_Nac)
  lista2.append(choice2)
  choice3=random.choice(Deporte)
  lista3.append(choice3)
  choice4=random.choice(Estado_Civil)
  lista4.append(choice4)
  choice5=random.choice(Grado_educ)
  lista5.append(choice5)
  choice6=random.choice(Sexo)
  lista6.append(choice6)
  choice7=random.choice(Genero_Musical)
  lista7.append(choice7)
  choice8=random.choice(Genero_Pelicula)
  lista8.append(choice8)

Ingrese la altura para 38: 1.70
Ingrese Salario: 350000
Ingrese la cantidad de hijos: 4
Ingrese la altura para 12: 1.40
Ingrese la altura para 10: 1.50

In [17]:
data={'Edad':edades,'Localidad':lista1,'Pais':lista2,'Deporte':lista3,'Estado_Civil':lista4,'Grado_educ':lista5,'Sexo':lista6,'Genero_musical':lista7,'Genero_pelicula':lista8}

df=pd.DataFrame(data)

df

,Edad,Localidad,Pais,Deporte,Estado_Civil,Grado_educ,Sexo,Genero_musical,Genero_pelicula
0,38,Ñuñoa,Brasil,Padel,Union Civil,Básica Completa,Masculino,Rap,Musical
1,12,Peñalolen,Brasil,Futbol,Soltero,Básica Incompleta,Femenino,Electronica,Romantica
2,10,Ñuñoa,Gales,Basketball,Union Civil,Básica Completa,Masculino,Rap,Suspenso

In [18]:
df['Precio']=df.sum(axis=0) #Solojugando a agregar columnas con valores

In [19]:
df

,Edad,Localidad,Pais,Deporte,Estado_Civil,Grado_educ,Sexo,Genero_musical,Genero_pelicula,Precio
0,38,Ñuñoa,Brasil,Padel,Union Civil,Básica Completa,Masculino,Rap,Musical,NaN
1,12,Peñalolen,Brasil,Futbol,Soltero,Básica Incompleta,Femenino,Electronica,Romantica,NaN
2,10,Ñuñoa,Gales,Basketball,Union Civil,Básica Completa,Masculino,Rap,Suspenso,NaN

In [ ]:
print(Salario)
print(edades)

['0', '1', '2', '3', '4', '5', '0', '6', '7', '0', '0', '0', '8', '9', '1000', '2000', '3000', '7000', '5000', '2000']
[4, 51, 46, 62, 36, 42, 17, 64, 28, 5, 9, 15, 18, 61, 55, 49, 66, 43, 19, 73]

In [6]:
Localidad=["Peñalolen","Las Condes","Maipu","La Florida","Ñuñoa","Colina"]
lista=[]
for i in range(20):
  choice=random.choice(Localidad)
  lista.append(choice)
lista

20