# Emisiones contaminantes

# 1. DB setup

Generar un DataFrame con los datos de los cuatro ficheros.

In [ ]:
import pandas as pd

In [ ]:
df16 = pd.read_csv('emisiones-2016.csv', sep=';')
df17 = pd.read_csv('emisiones-2017.csv', sep=';')
df18 = pd.read_csv('emisiones-2018.csv', sep=';')
df19 = pd.read_csv('emisiones-2019.csv', sep=';')

In [ ]:
df = pd.concat([df16, df17, df18, df19], axis=0)
df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANO,MES,D01,V01,D02,...,D27,V27,D28,V28,D29,V29,D30,V30,D31,V31
0,28,79,4,1,28079004_1_38,2016,1,8.0,V,7.0,...,9.0,V,7.0,V,8.0,V,9.0,V,9.0,V
1,28,79,4,1,28079004_1_38,2016,2,12.0,V,13.0,...,7.0,V,8.0,V,9.0,V,0.0,N,0.0,N
2,28,79,4,1,28079004_1_38,2016,3,11.0,V,10.0,...,8.0,V,7.0,V,8.0,V,10.0,V,8.0,V
3,28,79,4,1,28079004_1_38,2016,4,8.0,V,9.0,...,9.0,V,8.0,V,8.0,V,8.0,V,0.0,N
4,28,79,4,1,28079004_1_38,2016,5,7.0,V,8.0,...,7.0,V,7.0,V,7.0,V,7.0,V,7.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,28,79,60,14,28079060_14_6,2019,8,94.0,V,104.0,...,88.0,V,90.0,V,99.0,V,108.0,V,98.0,V
1832,28,79,60,14,28079060_14_6,2019,9,88.0,V,82.0,...,54.0,V,68.0,V,70.0,V,55.0,V,0.0,N
1833,28,79,60,14,28079060_14_6,2019,10,44.0,V,75.0,...,28.0,V,33.0,V,16.0,V,19.0,V,47.0,V
1834,28,79,60,14,28079060_14_6,2019,11,41.0,V,55.0,...,55.0,V,52.0,V,47.0,V,56.0,V,0.0,N
1835,28,79,60,14,28079060_14_6,2019,12,47.0,V,53.0,...,17.0,V,13.0,V,14.0,V,5.0,V,4.0,V

Filtrar las columnas del DataFrame para quedarse con las columnas ESTACION, MAGNITUD, A√ëO, MES y las correspondientes a los d√≠as D01, D02, etc.

In [ ]:
df.columns

Index(['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO',
       'ANO', 'MES', 'D01', 'V01', 'D02', 'V02', 'D03', 'V03', 'D04', 'V04',
       'D05', 'V05', 'D06', 'V06', 'D07', 'V07', 'D08', 'V08', 'D09', 'V09',
       'D10', 'V10', 'D11', 'V11', 'D12', 'V12', 'D13', 'V13', 'D14', 'V14',
       'D15', 'V15', 'D16', 'V16', 'D17', 'V17', 'D18', 'V18', 'D19', 'V19',
       'D20', 'V20', 'D21', 'V21', 'D22', 'V22', 'D23', 'V23', 'D24', 'V24',
       'D25', 'V25', 'D26', 'V26', 'D27', 'V27', 'D28', 'V28', 'D29', 'V29',
       'D30', 'V30', 'D31', 'V31'],
      dtype='object')

In [ ]:
non_day_cols = ['ESTACION', 'MAGNITUD', 'ANO', 'MES']
day_cols = ['D01', 'D02', 'D03', 'D04',
       'D05', 'D06', 'D07', 'D08', 'D09', 'D10', 'D11', 'D12', 'D13', 'D14',
       'D15', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24',
       'D25', 'D26', 'D27', 'D28', 'D29', 'D30', 'D31']

df = df[non_day_cols + day_cols]
df.head()

,ESTACION,MAGNITUD,ANO,MES,D01,D02,D03,D04,D05,D06,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,4,1,2016,1,8.0,7.0,6.0,6.0,7.0,6.0,...,10.0,11.0,11.0,13.0,12.0,9.0,7.0,8.0,9.0,9.0
1,4,1,2016,2,12.0,13.0,9.0,9.0,11.0,9.0,...,11.0,10.0,9.0,8.0,7.0,7.0,8.0,9.0,0.0,0.0
2,4,1,2016,3,11.0,10.0,9.0,9.0,7.0,8.0,...,8.0,8.0,9.0,9.0,9.0,8.0,7.0,8.0,10.0,8.0
3,4,1,2016,4,8.0,9.0,9.0,8.0,8.0,9.0,...,8.0,8.0,8.0,8.0,9.0,9.0,8.0,8.0,8.0,0.0
4,4,1,2016,5,7.0,8.0,9.0,9.0,8.0,8.0,...,7.0,7.0,8.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0

# 2. Separaci√≥n columna

Reestructurar el DataFrame para que los valores de los contaminantes de las columnas de los d√≠as aparezcan en una √∫nica columna.

In [ ]:
df = df.melt(id_vars=non_day_cols, var_name='DIA', value_name='EMISIONES')
df

        ESTACION  MAGNITUD   ANO  MES  DIA  EMISIONES
0              4         1  2016    1  D01        8.0
1              4         1  2016    2  D01       12.0
2              4         1  2016    3  D01       11.0
3              4         1  2016    4  D01        8.0
4              4         1  2016    5  D01        7.0
...          ...       ...   ...  ...  ...        ...
225241        60        14  2019    8  D31       98.0
225242        60        14  2019    9  D31        0.0
225243        60        14  2019   10  D31       47.0
225244        60        14  2019   11  D31        0.0
225245        60        14  2019   12  D31        4.0

[225246 rows x 6 columns]

# 3. Concatenaci√≥n fecha

A√±adir una columna con la fecha a partir de la concatenaci√≥n del a√±o, el mes y el d√≠a (usar el m√≥dulo datetime).

In [ ]:
from datetime import datetime

In [ ]:
def concatefecha(fila):
    return datetime(f"{fila['ANO']}-{fila['MES']}-{fila['DIA'][1:]}")
df['FECHA'] = df.apply(concatefecha, axis=0)
df

KeyError: ignored

# 4. Ordenamiento final

Eliminar las filas con fechas no v√°lidas (utilizar la funci√≥n isnat del m√≥dulo numpy) y ordenar el DataFrame por estaciones, contaminantes y fecha.